name: docs
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install ford fypp
    - run: ford ford.md
    - uses: JamesIves/github-pages-deploy-action@3.7.1
      if: github.event_name == 'push' && github.repository == 'awvwgk/stdlib_string' && ( startsWith( github.ref, 'refs/tags/' ) || github.ref == 'refs/heads/main' )
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: API-doc
        CLEAN: true
